In [1]:
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import random
import math



In [2]:
def getMatrix(width,height):
    i=0
    j=0
    while i<width:
        while j<height:
            #print('i=',i)
            #print('j=',j)
            I[i,j]=img_gray.getpixel((i,j))#[0]
            j+=1
        j=0
        i+=1


In [3]:
img_rgb = Image.open('C:\\Users\\Biswarup Mistry\\Desktop\\COMPANY\\Design_Work\\Images\\original_lena.png')
img_gray = img_rgb.convert('L')
#img_gray.save('erock_gray.jpg')
plt.imshow(img_gray) #, cmap=plt.cm.gray, interpolation='nearest'
plt.title('index.jpg')
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: '/home/biswarup/Desktop/jnotes/C:\\Users\\Biswarup Mistry\\Desktop\\COMPANY\\Design_Work\\Images\\original_lena.png'

In [18]:
width, height = img_gray.size
print('Image size : ',height,'*',width)
I=np.matrix(np.arange(width*height).reshape(width, height))
getMatrix(width,height)
print('Matrix PXL :\n',I)

Image size :  512 * 512
Matrix PXL :
 [[162 162 162 ...  43  44  44]
 [162 162 162 ...  43  44  44]
 [162 162 162 ...  50  55  55]
 ...
 [170 170 170 ... 104 104 104]
 [155 155 155 ... 100 105 105]
 [128 128 128 ...  98 108 108]]


In [4]:
# Changing Block
x=[]
y=[]
a=[]
k=0
#while k<height:
    #i=0
    #while i<width:
        #if (i+1)<width :
        #    x.append(I[k,i])
        #    y.append(I[k,(i+1)])
        #i+=1
    #print(k)
    #k+=1

i=j=0
while i<height: 
    j=0
    while j<width:
        a.append(I[i,j])
        j+=1
    i+=1
    
i=j=0
while (i+1)<len(a): 
    x.append(a[i])
    y.append(a[i+1])
    i+=1
    
#print('a : ',a)
#print('x : ',x)
#print('y : ',y)
print('len(x) : ',len(x))
print('len(a) : ',len(a))

NameError: name 'height' is not defined

In [5]:
def pearson_corr():
    k_x=[]
    k_y=[]
    k_x_sq=[]
    k_y_sq=[]
    l=[]
    sum_x=np.sum(x)
    sum_y=np.sum(y)
    x_bar=sum_x/len(x)
    y_bar=sum_y/len(y)
    for i in x:
        k_x.append(i-x_bar)
    for i in y:
        k_y.append(i-y_bar)
    for i in k_x:
        k_x_sq.append(i*i)
    for i in k_y:
        k_y_sq.append(i*i)
    sum_k_x_sq=np.sum(k_x_sq)
    std_dv_x=sum_k_x_sq/len(x)
    sum_k_y_sq=np.sum(k_y_sq)
    std_dv_y=sum_k_y_sq/len(y)
    i=0
    while i<len(x):
        l.append(k_x[i]*k_y[i])
        i+=1
    sum_of_l=np.sum(l)
    cov_x_y=sum_of_l/len(x)
    #pears_corr=cov_x_y/((math.sqrt(std_dv_x))*(math.sqrt(std_dv_y)))
    pears_corr=float("{:.8f}".format(cov_x_y/((math.sqrt(std_dv_x))*(math.sqrt(std_dv_y)))))
    return pears_corr

In [6]:
print(pearson_corr())

nan


/tmp/ipykernel_5558/3095934173.py:9: RuntimeWarning: invalid value encountered in scalar divide
  x_bar=sum_x/len(x)
/tmp/ipykernel_5558/3095934173.py:10: RuntimeWarning: invalid value encountered in scalar divide
  y_bar=sum_y/len(y)
/tmp/ipykernel_5558/3095934173.py:20: RuntimeWarning: invalid value encountered in scalar divide
  std_dv_x=sum_k_x_sq/len(x)
/tmp/ipykernel_5558/3095934173.py:22: RuntimeWarning: invalid value encountered in scalar divide
  std_dv_y=sum_k_y_sq/len(y)
/tmp/ipykernel_5558/3095934173.py:28: RuntimeWarning: invalid value encountered in scalar divide
  cov_x_y=sum_of_l/len(x)


In [7]:
r = np.corrcoef(x, y)
r

/home/biswarup/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/home/biswarup/anaconda3/lib/python3.12/site-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/home/biswarup/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2889: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/home/biswarup/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/home/biswarup/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)


array([[nan, nan],
       [nan, nan]])