In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from numpy import *
import math


In [2]:
data=pd.read_csv(r'E:\College_Notes\PG\Sem-3\DesignWork\DATA_sets\forestfires.csv')#'https://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/forestfires.csv')
#data.head(10)
#df=pd.DataFrame(data)
data.drop(['month','day'],inplace=True, axis=1)
data.head(5)

X  Y  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [13]:
i=0
arr=[]
for col in data:
    arr.append(col)
    i+=1
i=0

def pearson_corr(fi,fj):
    x=data[fi]
    y=data[fj]
    k_x=[]
    k_y=[]
    k_x_sq=[]
    k_y_sq=[]
    l=[]
    sum_x=np.sum(x)
    sum_y=np.sum(y)
    x_bar=sum_x/len(x)
    y_bar=sum_y/len(y)
    for i in x:
        k_x.append(i-x_bar)
    for i in y:
        k_y.append(i-y_bar)
    for i in k_x:
        k_x_sq.append(i*i)
    for i in k_y:
        k_y_sq.append(i*i)
    sum_k_x_sq=np.sum(k_x_sq)
    std_dv_x=sum_k_x_sq/len(x)
    sum_k_y_sq=np.sum(k_y_sq)
    std_dv_y=sum_k_y_sq/len(y)
    i=0
    while i<len(x):
        l.append(k_x[i]*k_y[i])
        i+=1
    sum_of_l=np.sum(l)
    cov_x_y=sum_of_l/len(x)
    #pears_corr=cov_x_y/((math.sqrt(std_dv_x))*(math.sqrt(std_dv_y)))
    pears_corr=float("{:.2f}".format(cov_x_y/((math.sqrt(std_dv_x))*(math.sqrt(std_dv_y)))))
    return pears_corr


In [14]:
matrix=[]
for row in data:
    a=[]
    for col in data:
        a.append(pearson_corr(row,col))
    matrix.append(a)

#R=len(arr)
#C=R
#for i in range(R):
#    for j in range(C): 
#        print(matrix[i][j], end = " ")
#    print() 


In [15]:
#np.matrix=matrix
#print(np.matrix)

out_arr=np.vstack(matrix)
print(out_arr)

[[ 1.    0.54 -0.02 -0.05 -0.09  0.01 -0.05  0.09  0.02  0.07  0.06]
 [ 0.54  1.   -0.05  0.01 -0.1  -0.02 -0.02  0.06 -0.02  0.03  0.04]
 [-0.02 -0.05  1.    0.38  0.33  0.53  0.43 -0.3  -0.03  0.06  0.04]
 [-0.05  0.01  0.38  1.    0.68  0.31  0.47  0.07 -0.11  0.07  0.07]
 [-0.09 -0.1   0.33  0.68  1.    0.23  0.5  -0.04 -0.2   0.04  0.05]
 [ 0.01 -0.02  0.53  0.31  0.23  1.    0.39 -0.13  0.11  0.07  0.01]
 [-0.05 -0.02  0.43  0.47  0.5   0.39  1.   -0.53 -0.23  0.07  0.1 ]
 [ 0.09  0.06 -0.3   0.07 -0.04 -0.13 -0.53  1.    0.07  0.1  -0.08]
 [ 0.02 -0.02 -0.03 -0.11 -0.2   0.11 -0.23  0.07  1.    0.06  0.01]
 [ 0.07  0.03  0.06  0.07  0.04  0.07  0.07  0.1   0.06  1.   -0.01]
 [ 0.06  0.04  0.04  0.07  0.05  0.01  0.1  -0.08  0.01 -0.01  1.  ]]


In [16]:
print(matrix[2][3])

0.38


In [17]:
data.corr()

X         Y      FFMC       DMC        DC       ISI      temp  \
X     1.000000  0.539548 -0.021039 -0.048384 -0.085916  0.006210 -0.051258   
Y     0.539548  1.000000 -0.046308  0.007782 -0.101178 -0.024488 -0.024103   
FFMC -0.021039 -0.046308  1.000000  0.382619  0.330512  0.531805  0.431532   
DMC  -0.048384  0.007782  0.382619  1.000000  0.682192  0.305128  0.469594   
DC   -0.085916 -0.101178  0.330512  0.682192  1.000000  0.229154  0.496208   
ISI   0.006210 -0.024488  0.531805  0.305128  0.229154  1.000000  0.394287   
temp -0.051258 -0.024103  0.431532  0.469594  0.496208  0.394287  1.000000   
RH    0.085223  0.062221 -0.300995  0.073795 -0.039192 -0.132517 -0.527390   
wind  0.018798 -0.020341 -0.028485 -0.105342 -0.203466  0.106826 -0.227116   
rain  0.065387  0.033234  0.056702  0.074790  0.035861  0.067668  0.069491   
area  0.063385  0.044873  0.040122  0.072994  0.049383  0.008258  0.097844   

            RH      wind      rain      area  
X     0.085223  0.018798  0.065387  0.063385  
Y     0.062221 -0.020341  0.033234  0.044873  
FFMC -0.300995 -0.028485  0.056702  0.040122  
DMC   0.073795 -0.105342  0.074790  0.072994  
DC   -0.039192 -0.203466  0.035861  0.049383  
ISI  -0.132517  0.106826  0.067668  0.008258  
temp -0.527390 -0.227116  0.069491  0.097844  
RH    1.000000  0.069410  0.099751 -0.075519  
wind  0.069410  1.000000  0.061119  0.012317  
rain  0.099751  0.061119  1.000000 -0.007366  
area -0.075519  0.012317 -0.007366  1.000000

In [ ]:
axis_corr = sns.heatmap(
d,
vmin=-1, vmax=1, center=0,
cmap=sns.diverging_palette(50, 500, n=500),
square=True
)

plt.show()